### ISSUE TITLE
Allow notifications to bypass Do Not Disturb Mode

### ISSUE THREAD

**Issue by Offpics** [binwiederhier/ntfy-android#23]
I always have my phone on do not disturb mode. I would like Max Priority Notifications to bypass this mode, so I can receive sound notifications all the time :). 

I know it's possible on android, and I'm wondering whether you have plans to add a support for it.

**Comment by binwiederhier** [comment]
I like the idea, which is why I created a ticket a whole back https://github.com/binwiederhier/ntfy/issues/91

I'm closing this as a duplicate. You can comment or upvote the other ticket if you like.
