### ISSUE TITLE
Question (not bug)

### ISSUE THREAD

**Issue by apprenticius** [binwiederhier/ntfy-android#50]
What is the "state of the art" to integrate ntfy in other apps/projects? Copy the mechanism of this app or send somehow a broadcast intent from this app to other apps/project? Is there any example?
By the way: Great work. Exactly what I missed for long time.

**Comment by binwiederhier** [comment]
Please ask questions in the main issue tracker: https://github.com/binwiederhier/ntfy/issues
Merry Christmas :santa:
