### ISSUE TITLE
Support emojis as channel icons 

### ISSUE THREAD

**Issue by Matthias84** [binwiederhier/ntfy-android#65]
Hi, I would like to suggest not only to support local stored images to illustrate the channels, but also to support picking an emoji. The emojisets usually contain a lot of icons to underline the channel's intention and are optimized to be easy to recognize across different cultures etc. and support a lot of different aspects to illustrate the channels intent 🙂

* :house_with_garden:  smarthome
* :fire_extinguisher: security
* :lab_coat: lab
* ....

**Comment by binwiederhier** [comment]
Please open tickets in the main issue tracker, as per https://github.com/binwiederhier/ntfy-android/issues/1
