### ISSUE TITLE
Reproducible for F-Droid

### ISSUE THREAD

**Issue by linsui** [binwiederhier/ntfy-android#66]
Are you aware of https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13948?

**Comment by binwiederhier** [comment]
Yes this is me https://gitlab.com/binwiederhier

I just commented. A ntfy fan emailed me. That's how I became aware of this MR. Pretty scary stuff.

**Comment by terenc3** [comment]
Since fdroid is not getting any new build, i think it should be mentioned on the homepage and docs that this version is significant behind
