### ISSUE TITLE
Phone Numbers Not Clickable for Direct Calling in NTFY App in message

### ISSUE THREAD

**Issue by XylenSky** [binwiederhier/ntfy-android#68]
### Description:
Phone numbers in messages are not recognized as clickable links in the NTFY app. Users are unable to directly tap on phone numbers to initiate calls. This inconvenience affects the user experience by requiring manual copy-pasting of numbers into the dialer.

### Expected Behavior:
Phone numbers within messages should be formatted as clickable links. Tapping on these links should initiate phone calls directly from the NTFY app.

**Comment by binwiederhier** [comment]
Please open tickets in the main issue tracker, as per https://github.com/binwiederhier/ntfy-android/issues/1
