### ISSUE TITLE
Publish notification

### ISSUE THREAD

**Issue by mikrofyr** [binwiederhier/ntfy-android#72]
Hi, is it not possible to publish from Android app? 
If this is a missing feature I'll probably just use webapp on phone as well.

**Comment by wunter8** [comment]
There is a limited "publish" dialog accessible by "Share"ing text or files from another app (using Android's built-in Share feature). There are plans to make publishing from the app easier

**Comment by mikrofyr** [comment]
Thanks for confirming. Plan sounds good.
